title: Slings
description: My Personal Stack Problems
author: Anthony Febo
github: https://github.com/agusmakmun
about: Active Virgo and your friendly neighborhood Boricua. Exploring identity, representation, and crying. Soooo much crying
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: # /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/agusmakmun6"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/summonagus"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

share:
  twitter_username: agusmakmun6
  fb_appid: 1749788565247320

urls:
    - text: Slings
      url: /slings/
    - text: Notebooks
      url: /notebooks/
    - text: RSSFeed
      url: /feed.xml

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
